---
# Experiment configuration
total_epochs: 50
epochs_per_cycle: 1
wait_for_clients: true
net: Cifar10CNN
dataset: cifar10
# Use cuda is available; setting to false will force CPU
cuda: false
experiment_prefix: 'experiment_sample'
output_location: 'output'
tensor_board_active: true
# uses all clients per round
clients_per_round: 5
system:
  federator:
    hostname: '10.46.226.83'
    nic: 'wlp0s20f3'
  clients:
    amount: 5
